// library proj_ver1.variables;

String name = '';
String date = '';
String email = '';
String password = '';
String confpassword = '';
String currentPass = "";
String newPass = "";
String confnewPass = "";
String confDelete = "";
String start = '';
String end = '';
String room = '';
String color = '';
String plate = '';
String price = '';
String searchStart = '';
String searchEnd = '';
String searchDate = '';
bool isSwitchOnLoc = false;
bool isSwitchOnCam = false;
bool isSwitchOnSto = false;
bool isSwitchOnTex = true;
bool isSwitchOnEma = true;
bool isSwitchOnDev = true;
